### PR TITLE
Floorplans

### PR DESCRIPTION
**Pull request by AbishekSh**

### CODE REVIEW

**Review by Acumane — DISMISSED** [review]
- Commons, library, and Troy 2nd floor turned out well, good job @Awesomecar11
- @AbishekSh Ricketts 4-5 are good but there's a bit of a gap along the outer walls. @Awesomecar11 knows how to fix this 
- Troy is scuffed (floor 1 is small, stroke width on 3 is large. See 2 as reference)
- Low has quite a few problems

**Comment by AbishekSh** [comment]
Ricketts Floor 4 and 5 have been fixed
Ricketts4.svg
Ricketts5.svg

**Comment by Acumane** [comment]
Please squash related commits

**Review by paulbruzzi — APPROVED** [review]
The winslow building will need to be updated at a later date

**Pull request merged**
